### ISSUE TITLE
Delete node-modules

### ISSUE THREAD

**Issue by johnnydevelops** [JoshnaksPNG/Bad_Apple_Youtube_Page#1]
Node-modules will be automatically recreated by running "npm i" due to the package.json file. Deleting node-modules will decrease the file size drastically

**Comment by Rudxain** [comment]
Fixed in [this commit](https://github.com/JoshnaksPNG/Bad_Apple_Youtube_Page/commit/ab3ef5348a34e50bc7167ee5c229be098cfeeb18)

Please, @JoshnaksPNG & @johnnydevelops, one of you should close this issue
